music_inference_model_output = [
    ['InputLayer', [(None, 1, 90)], 0],
    ['InputLayer', [(None, 64)], 0],
    ['InputLayer', [(None, 64)], 0],
    ['LSTM', [(None, 64), (None, 64), (None, 64)], 39680, [(None, 1, 90), (None, 64), (None, 64)], 'tanh'],
    ['Dense', (None, 90), 5850, 'softmax'],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
    ['TFOpLambda', (None, ), 0],
    ['TFOpLambda', (None, 90), 0],
    ['RepeatVector', (None, 1, 90), 0, 1],
]

djmodel_output = [
    ['InputLayer', [(None, 30, 90)], 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['Reshape', (None, 1, 90), 0],
    ['InputLayer', [(None, 64)], 0],
    ['InputLayer', [(None, 64)], 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['LSTM', [(None, 64), (None, 64), (None, 64)], 39680, [(None, 1, 90), (None, 64), (None, 64)], 'tanh'],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['SlicingOpLambda', (None, 90), 0],
    ['Dense', (None, 90), 5850, 'softmax'],
]
